#!/usr/bin/env python3
"""Generate project-status.qmd from hierarchical status JSON files."""
from pathlib import Path
import json
from datetime import datetime
from model_reliability.status import write_case_status

ROOT = Path(__file__).resolve().parents[1]

def read_json(path):
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return {"status": "error", "error": str(exc)}

def artifact_status(path):
    if not path.exists():
        return "missing"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return "error"
    return data.get("status", "present")

def document_id(doc):
    value = doc.get("document_id", doc.get("id"))
    return "" if value is None else str(value)

def expected_raw_path(case_dir, doc):
    raw = doc.get("expected_raw_path") or doc.get("raw_path")
    if raw:
        path = Path(str(raw))
        return path if path.is_absolute() else case_dir / path
    return case_dir / "corpus" / "raw" / f"{document_id(doc)}.txt"

def expected_text_path(case_dir, doc):
    return case_dir / "corpus" / "text" / f"{document_id(doc)}.md"

def expected_segmented_path(case_dir, doc):
    return case_dir / "corpus" / "segmented" / f"{document_id(doc)}.json"

def expected_mipvu_path(case_dir, doc):
    return case_dir / "corpus" / "mipvu" / f"{document_id(doc)}_mipvu.json"

def expected_annotated_path(case_dir, doc):
    return case_dir / "corpus" / "annotated" / f"{document_id(doc)}_annotated.json"

def count_expected(docs, resolver):
    return len([doc for doc in docs if resolver(doc).is_file()])

def main():
    project = read_json(ROOT / "status/project-status.json")
    cases = []
    cases_root = ROOT / "cases"
    if cases_root.exists():
        for case_dir in sorted(cases_root.iterdir()):
            if not case_dir.is_dir():
                continue
            status = read_json(case_dir / "status" / "case-status.json")
            if not status:
                status = read_json(case_dir / "status" / "x-case-status.json")
            if (case_dir / "metadata" / "document-manifest.json").exists():
                manifest = read_json(case_dir / "metadata" / "document-manifest.json")
                docs = manifest.get("documents", []) if isinstance(manifest, dict) else []
                stage_counts = {
                    "manifest": len(docs) if isinstance(docs, list) else 0,
                    "raw": count_expected(docs, lambda doc: expected_raw_path(case_dir, doc)),
                    "text": count_expected(docs, lambda doc: expected_text_path(case_dir, doc)),
                    "segmented": count_expected(docs, lambda doc: expected_segmented_path(case_dir, doc)),
                    "mipvu": count_expected(docs, lambda doc: expected_mipvu_path(case_dir, doc)),
                    "annotated": count_expected(docs, lambda doc: expected_annotated_path(case_dir, doc)),
                    "concordance": artifact_status(case_dir / "analysis" / "concordance.json"),
                    "analysis": artifact_status(case_dir / "analysis" / "analysis.json"),
                }
            else:
                stage_counts = {
                    "manifest": "",
                    "raw": "",
                    "text": "",
                    "segmented": "",
                    "mipvu": "",
                    "annotated": "",
                    "concordance": artifact_status(case_dir / "synthesis" / "shared-concordance.json"),
                    "analysis": artifact_status(case_dir / "status" / "x-case-status.json"),
                }
            if (case_dir / "metadata" / "document-manifest.json").exists():
                reliability = write_case_status(ROOT, case_dir.name)
            else:
                reliability = {"state": "not-applicable", "warnings": []}
            cases.append((
                case_dir.name,
                status.get("status", "unknown"),
                status.get("current_stage", ""),
                reliability,
                stage_counts,
            ))

    rows = "\n".join(
        "| `{cid}` | {status} | {stage} | {reliability} | {manifest} | {raw} | {text} | {segmented} | {mipvu} | {annotated} | {concordance} | {analysis} |".format(
            cid=cid,
            status=status,
            stage=stage,
            reliability=reliability["state"],
            **counts,
        )
        for cid, status, stage, reliability, counts in cases
    )
    reliability_notes = "\n".join(
        f"- `{cid}` ({reliability['state']}): {warning}"
        for cid, _, _, reliability, _ in cases
        for warning in reliability["warnings"]
    ) or "- No model-reliability warnings."
    content = f"""---
title: "Project Status"
---

::: {{.callout-note}}
Generated by `scripts/generate-project-status.py` on {datetime.now().isoformat()}.
:::

## Current milestone

{project.get("current_milestone", "unknown")}

## Case status

| Case | Status | Current stage | Model reliability | Manifest docs | Raw | Text | Segmented | MIPVU | Annotated | Concordance | Analysis |
|---|---|---|---|---:|---:|---:|---:|---:|---:|---|---|
{rows}

## Model-reliability warnings

{reliability_notes}

## Notes

{project.get("notes", "")}
"""
    (ROOT / "project-status.qmd").write_text(content, encoding="utf-8")
    print("Wrote project-status.qmd")

if __name__ == "__main__":
    main()
